camera:
  device_id: 4
  width: 1280
  height: 720
  fps: 30

detection:
  confidence_threshold: 0.5
  min_object_size: 50  # pixels

storage:
  local:
    base_path: "/path/to/storage"
    max_files: 1000
    cleanup_threshold: 0.9  # 90% full

aws:
  region: "your-region"
  bucket: "your-bucket-name"
  upload_interval: 300  # seconds